steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: [ '-c', 'docker login --username=jderuere --password=$$PASSWORD' ]
    secretEnv: [ 'PASSWORD' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'jderuere/cimg-argocd:$TAG_NAME', '--build-arg', 'image_to_build=argocd', 'docker' ]
images: [ 'jderuere/cimg-argocd:$TAG_NAME' ]
timeout: 1800s

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-hub-password/versions/latest
      env: 'PASSWORD'

options:
  logging: CLOUD_LOGGING_ONLY